#!/bin/bash

############################
#
# Redshift Reader for Zabbix
#
# This script will be able to read informateion collected on batch files
#
# by julio.hegedus@sentia.com ## 07-08-2018
#
#

LOCAL=$(dirname $0)

BATCH=$LOCAL/redfish/$1
ITEM=$2

if [[ -z ${BATCH} || -z ${ITEM} ]]; then
  echo "You must me gimme something dude! wth!"
  echo "Try: $0 somehostname.nameofobject.json Status.Health"
  exit 1
fi

if [ ! -f ${BATCH} ]; then
  echo "no batch file yet"
  exit 1
else
  RES=`cat ${BATCH} | jq ".${ITEM}" | tr -d "'" | tr -d '"'`
  if [[ -z $RES ]]; then
    echo "0"
  else
    echo $RES
  fi
  exit 0
fi
